language: r
os: linux
dist: xenial

cache:
  packages: yes

r_packages:
  - devtools
  - testthat
  - roxygen2
  - covr

addons:
  apt:
    packages:
      - libproj-dev
      - libgdal-dev
      - libgeos-dev
      - r-cran-ncdf4
      - libv8-3.14-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libnetcdf-dev
      - libjq-dev

after_success:
  - Rscript -e 'covr::coveralls()'
