language: r
os: linux
dist: bionic

cache:
  packages: yes

r_packages:
  - devtools
  - testthat
  - roxygen2
  - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev

addons:
  apt:
    packages:
      - libv8-3.14-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libnetcdf-dev
      - libjq-dev

after_success:
  - Rscript -e 'covr::coveralls()'
