language: r
dist: trusty
sudo: false

cache:
  packages: yes

r_packages:
  - testthat
  - roxygen2

addons:
  apt:
    packages:
      - gdal-bin
      - libproj-dev
      - gcc-4.8
      - libv8-3.14-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libudunits2-dev

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ppa --yes
    - sudo add-apt-repository -y ppa:opencpu/jq
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libjq-dev
